spring.application.name: core-api
#spring.profiles.active: local
spring.profiles.active: local-dev

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - monitoring.yml
      - logging.yml
      - db-core.yml
      - client-example.yml
      - infra.yml
      - ai-core.yml
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

  messages:
    basename: messages, errors
    encoding: UTF-8

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
    accesslog:
      ipv6-canonical: false
  port: 8080
  shutdown: graceful

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

